[package]
name = "colors-transform"
version = "0.1.0"
description = "Lib for covert and transform colors"
authors = ["mz <emgyrz@gmail.com>"]
license = "MIT"
homepage = "https://github.com/emgyrz/colors.rs"
repository = "https://github.com/emgyrz/colors.rs.git"
keywords = ["colors", "converter", "css", "rgb", "hsl"]
graphics = [ "graphics"]
edition = "2018"

[dependencies]
