[package]
name = "colors-transform"
version = "0.2.10"
description = "Module for convert and transform colors"
authors = ["mz <emgyrz@gmail.com>"]
license = "MIT"
homepage = "https://github.com/emgyrz/colors.rs"
repository = "https://github.com/emgyrz/colors.rs.git"
keywords = ["colors", "converter", "css", "rgb", "hsl"]
categories = [ "graphics"]
edition = "2018"
readme = "README.md"

[dependencies]
